#!/usr/bin/env python
# coding:utf-8

lucky_num = 30
count = 0

for i in range(3):
    input_num = int(input('Please input your lucky number?'))
    if input_num < lucky_num:
        print('The real nums is smaller!')
    elif input_num > lucky_num:
        print('The real nums is bigger')
    else:
        print('Bingo')
        break
else:
    print('Too many errors to try!\nBye!')

